### PR TITLE
Add validate_custom target to Makefile

### PR DESCRIPTION
**Pull request by Docproc**
This allows the use of non-core JSON evidence, i.e. evidence which is not part of the public Open Targets build, without the need to run the step outside of the Makefile or to modify any code.

The file is specified via the CUSTOM_JSON environment variable, e.g. 

`make "CUSTOM_JSON_FILE=$(pwd)/json/custom.json.gz" validate_custom`

### CODE REVIEW

**Comment by afaulconbridge** [comment]
> Do you mean having `validate_all` check if `CUSTOM_JSON` is set and if so, run the custom validation along with all the others?

@Docproc Yes, in short.

Thinking about this some more, I'm beginning to form the opinion that with opentargets/platform#146 and specifically opentargets/platform#115 this might not be necessary at all - instead the preferred way to handle additional (or alternative) evidence would be through the configuration file, not additional steps on the makefile. We should have a chat about this when you're in in person.

**Comment by Docproc** [comment]
I forgot to mention this - will the upcoming config changes mean that evidence can be specified in the config (file/var)? If not, or if it's going to be a while before it does, it would be good to have this PR merged.

**Comment by afaulconbridge** [comment]
@Docproc With the configuration changes in 19.04 is this PR still relevant? I'll close it if not.

**Comment by afaulconbridge** [comment]
After discussion, this functionallity can be done via the data config file. Therefore, I am closing this PR.

**Pull request closed without merging**
