### PR TITLE
post globalstats

### PR DESCRIPTION
**Pull request by mkarmona**

### CODE REVIEW

**Comment by AsierGonzalez** [comment]
Hi, I'm not reviewing this and I wasn't involved in the decission making so apologise if you discussed this already, but are we stopping the propagation of evidence from atlas but allowing that from europepmc? It feels as we could end up with a similar but exacerbated problem given that there is so much evidence coming from literature.

**Comment by MichaelaEBI** [comment]
@mkarmona I will run this branch today to see whether the propagation/non-propagation works.

**Comment by afaulconbridge** [comment]
In order for @MichaelaEBI to run this cleanly, PRs opentargets/data_pipeline#378 and opentargets/data_pipeline#379 need to be merged first. Ideally, also opentargets/data_pipeline#364 to make it run faster.

**Comment by mkarmona** [comment]
@AsierGonzalez we did it on purpose. this change was deliberately made to let EPMC propagates as many of the single associations coming from EPMC are probably genuine

**Comment by afaulconbridge** [comment]
Now that the other pull requests have been merged to master, I'm going to update this one and run it so @MichaelaEBI can take a look to assess the impact

**Comment by afaulconbridge** [comment]
@mkarmona please don't close pull requests without waiting for the review to complete.

**Comment by mkarmona** [comment]
true! sorry about that


Saludos,
Miguel Carmona
PGP PUBLIC KEY
<https://pgp.mit.edu/pks/lookup?op=vindex&search=0x12959B27D96C797D>

**Pull request merged**
